[package]
name = "master_render_3d"
version = "0.2.0"
edition = "2021"

[target.x86_64-unknown-linux-gnu]
linker = "C:/cygwin64/bin/gcc.exe"

[dependencies]
image_helper = { path = "image_helper" }
png = "0.17.14"